FROM alpine:3.17.2

LABEL maintainer="Maksim Bunegin"
LABEL description="Common net utils (Alpine)"
LABEL website="https://github.com/steap0/docker-net-tools"

RUN apk --no-cache add  bind-tools \
                        busybox-extras \
                        curl \
                        iproute2 \
                        nmap \
                        wget
